### ISSUE TITLE
state_dict runtime error

### ISSUE THREAD

**Issue by RS0099** [t04glovern/icface#2]
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model = create_model(opt)
  File "/gdrive/Shared drives/Wk_unknown/face_recog/attempt_2/icface/src/models/models.py", line 18, in create_model
    model.initialize(opt)
  File "/gdrive/Shared drives/Wk_unknown/face_recog/attempt_2/icface/src/models/pix2pix_model.py", line 68, in initialize
    self.load_network(self.netG, 'G', opt.which_epoch)
  File "/gdrive/Shared drives/Wk_unknown/face_recog/attempt_2/icface/src/models/base_model.py", line 60, in load_network
    network.load_state_dict(new_state_dict)
  File "/usr/local/envs/icface/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.model.1.weight", "module.model.2.weight", "module.model.2.bias", "module.model.2.running_mean", "module.model.2.running_var", "module.model.4.weight", "module.model.5.weight", "module.model.5.bias", "module.model.5.running_mean", "module.model.5.running_var", "module.model.7.weight", "module.model.8.weight", "module.model.8.bias", "module.model.8.running_mean", "module.model.8.running_var", "module.model.10.conv_block.1.weight", "module.model.10.conv_block.2.weight", "module.model.10.conv_block.2.bias", "module.model.10.conv_block.2.running_mean", "module.model.10.conv_block.2.running_var", "module.model.10.conv_block.6.weight", "module.model.10.conv_block.7.weight", "module.model.10.conv_block.7.bias", "module.model.10.conv_block.7.running_mean", "module.model.10.conv_block.7.running_var", "module.model.11.conv_block.1.weight", "module.model.11.conv_block.2.weight", "module.model.11.conv_block.2.bias", "module.model.11.conv_block.2.running_mean", "module.model.11.conv_block.2.running_var", "module.model.11.conv_block.6.weight", "module.model.11.conv_block.7.weight", "module.model.11.conv_block.7.bias", "module.model.11.conv_block.7.running_mean", "module.model.11.conv_block.7.running_var", "module.model.12.conv_block.1.weight", "module.model.12.conv_block.2.weight", "module.model.12.conv_block.2.bias", "module.model.12.conv_block.2.running_mean", "module.model.12.conv_block.2.running_var", "module.model.12.conv_block.6.weight", "module.model.12.conv_block.7.weight", "module.model.12.conv_block.7.bias", "module.model.12.conv_block.7.running_mean", "module.model.12.conv_block.7.running_var", "module.model.13.conv_block.1.weight", "module.model.13.conv_block.2.weight", "module.model.13.conv_block.2.bias", "module.model.13.conv_block.2.running_mean", "module.model.13.conv_block.2.running_var", "module.model.13.conv_block.6.weight", "module.model.13.conv_block.7.weight", "module.model.13.conv_block.7.bias", "module.model.13.conv_block.7.running_mean", "module.model.13.conv_block.7.running_var", "module.model.14.conv_block.1.weight", "module.model.14.conv_block.2.weight", "module.model.14.conv_block.2.bias", "module.model.14.conv_block.2.running_mean", "module.model.14.conv_block.2.running_var", "module.model.14.conv_block.6.weight", "module.model.14.conv_block.7.weight", "module.model.14.conv_block.7.bias", "module.model.14.conv_block.7.running_mean", "module.model.14.conv_block.7.running_var", "module.model.15.conv_block.1.weight", "module.model.15.conv_block.2.weight", "module.model.15.conv_block.2.bias", "module.model.15.conv_block.2.running_mean", "module.model.15.conv_block.2.running_var", "module.model.15.conv_block.6.weight", "module.model.15.conv_block.7.weight", "module.model.15.conv_block.7.bias", "module.model.15.conv_block.7.running_mean", "module.model.15.conv_block.7.running_var", "module.model.16.weight", "module.model.17.weight", "module.model.17.bias", "module.model.17.running_mean", "module.model.17.running_var", "module.model.19.weight", "module.model.20.weight", "module.model.20.bias", "module.model.20.running_mean", "module.model.20.running_var", "module.model.23.weight", "module.model.23.bias". 
	Unexpected key(s) in state_dict: "state_dict", "optimizer". 

I think this error is there due to the extra module. in dictionary keys. I have searched on net and tried the fix.

def load_network(self, network, network_label, epoch_label):
        save_filename = '%s_net_%s.pth' % (epoch_label, network_label)
        save_path = os.path.join(self.save_dir, save_filename)
        state_dict = torch.load(save_path)
        from collections import OrderedDict
        new_state_dict = OrderedDict()
        for k, v in state_dict.items():
            name = k.replace("module.", "") # remove `module.`
            new_state_dict[name] = v
        # load params
        network.load_state_dict(new_state_dict)

I changed the above in base_model.py but that didn;t work either.

Pls help!!

**Comment by RS0099** [comment]
The problem is that the state_dict itself has two dictionary by the name 'state_dict' ans 'optimizer'
So modifying the code to : 

  def load_network(self, network, network_label, epoch_label):
        save_filename = '%s_net_%s.pth' % (epoch_label, network_label)
        save_path = os.path.join(self.save_dir, save_filename)
        print(save_path)
        temp_state_dict = torch.load(save_path)
        from collections import OrderedDict
        new_state_dict = OrderedDict()
        for k, v in temp_state_dict.items():
          for i,j in v.items():
            if i!='param_groups' and i!='state':
              new_state_dict[i] = j
          # load params
        network.load_state_dict(new_state_dict)


works
